-- Create a unified table for trackng expenses and income
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    category TEXT NOT NULL, -- e.g., 'Office Rent', 'Client Payment', 'Stationery'
    amount DECIMAL(12, 2) NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    description TEXT,
    reference_number TEXT, -- Invoice no, Receipt no
    payment_method TEXT, -- 'Cash', 'Cheque', 'Online', 'Bank Transfer'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- Policies
-- Drop existing policies to handle updates cleanly
DROP POLICY IF EXISTS "authenticated_all_transactions" ON transactions;
DROP POLICY IF EXISTS "anon_all_transactions" ON transactions;

-- Allow authenticated users (Clerks, Admins) to do everything for now
CREATE POLICY "authenticated_all_transactions" ON transactions
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Allow anon access as well for local dev or if auth isn't fully set up for clerks yet
CREATE POLICY "anon_all_transactions" ON transactions
    FOR ALL
    TO anon
    USING (true)
    WITH CHECK (true);
