-- Create a unified table for trackng expenses and income
CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    category TEXT NOT NULL, -- e.g., 'Office Rent', 'Client Payment', 'Stationery'
    amount DECIMAL(12, 2) NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    description TEXT,
    reference_number TEXT, -- Invoice no, Receipt no
    payment_method TEXT, -- 'Cash', 'Cheque', 'Online', 'Bank Transfer'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- Policies
-- Allow authenticated users (Clerks, Admins) to do everything for now
-- In a real app, you might restrict deletion or updates to Admins

DROP POLICY IF EXISTS "authenticated_all_transactions" ON transactions;
CREATE POLICY "authenticated_all_transactions" ON transactions
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- Allow anon for dev access if needed (optional, safer to keep it authenticated)
-- If Dashboard is used without auth, enable this:
-- CREATE POLICY "anon_all_transactions" ON transactions FOR ALL TO anon USING (true) WITH CHECK (true);
