-- Drop previous table if exists to reset schema
DROP TABLE IF EXISTS public.interim_orders;

-- Create table mimicking the user's structure but with Postgres conventions
CREATE TABLE public.interim_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_name TEXT,
    case_no INTEGER,
    case_year INTEGER,
    undated_text TEXT, -- Maps to 'UnDated'
    next_date DATE,    -- Maps to 'NDate'
    order_date DATE,   -- Maps to 'Date'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.interim_orders ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow public read access" ON public.interim_orders
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow authenticated full access" ON public.interim_orders
    FOR ALL TO authenticated USING (true);
