-- Create case_copies table
CREATE TABLE IF NOT EXISTS public.case_copies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_name TEXT NOT NULL,
    case_no TEXT,
    case_year TEXT,
    doctype TEXT,
    date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.case_copies ENABLE ROW LEVEL SECURITY;

-- Allow public access (aligned with previous fix for custom auth)
CREATE POLICY "Allow public all case_copies" ON public.case_copies
FOR ALL TO public USING (true);

