-- Create case_names table
CREATE TABLE IF NOT EXISTS public.case_names (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.case_names ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access (needed for anon/custom auth)
CREATE POLICY "Allow public view case_names" ON public.case_names
FOR SELECT TO public USING (true);

-- Create policy for public insert (if needed later, but mainly for admin)
-- For now, we just need read access for the dropdown.

-- Insert initial data
INSERT INTO public.case_names (name) VALUES 
('CoC'),
('CrlMc'),
('CrlA'),
('CrlRP'),
('RP'),
('OP(Crl)'),
('OP(C)'),
('Trp(C)'),
('Trp(Crl)'),
('WA'),
('WP(C)'),
('WP(Crl)'),
('MACA'),
('MATA'),
('AR')
ON CONFLICT (name) DO NOTHING;
