-- Create the judgments table
CREATE TABLE IF NOT EXISTS public.judgments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_name TEXT NOT NULL,
    case_no TEXT NOT NULL,
    case_year TEXT NOT NULL,
    judge_name TEXT,
    judgment_date DATE,
    description TEXT,
    file_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.judgments ENABLE ROW LEVEL SECURITY;

-- Policy for Public Access (Since we are using custom auth that acts as public/anon)
CREATE POLICY "Allow public full access" ON public.judgments
    FOR ALL
    TO public
    USING (true)
    WITH CHECK (true);

-- Insert some sample data
INSERT INTO public.judgments (case_name, case_no, case_year, judge_name, judgment_date, description)
VALUES 
('WP(C)', '4504', '2017', NULL, '2026-02-11', NULL);
