CREATE TABLE IF NOT EXISTS releases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    features JSONB DEFAULT '[]'::jsonb
);

-- Enable RLS
ALTER TABLE releases ENABLE ROW LEVEL SECURITY;

-- Drop existing policies to avoid conflicts
DROP POLICY IF EXISTS "authenticated_view_releases" ON releases;
DROP POLICY IF EXISTS "authenticated_insert_releases" ON releases;
DROP POLICY IF EXISTS "public_view_releases" ON releases;
DROP POLICY IF EXISTS "public_insert_releases" ON releases;
DROP POLICY IF EXISTS "anon_view_releases" ON releases;
DROP POLICY IF EXISTS "anon_insert_releases" ON releases;

-- Policy: Allow EVERYONE (anon + authenticated) to view releases
CREATE POLICY "public_view_releases" ON releases
    FOR SELECT TO anon, authenticated
    USING (true);

-- Policy: Allow EVERYONE (anon + authenticated) to insert releases
-- (This is necessary because the Admin Dashboard might be running without a Supabase session)
CREATE POLICY "public_insert_releases" ON releases
    FOR INSERT TO anon, authenticated
    WITH CHECK (true);

-- Insert a sample release if table is empty (using a safe conditional insert)
INSERT INTO releases (version, title, description, features)
SELECT 'v1.0.0', 'Initial Launch', 'Welcome to the Kurup & Associates Legal Management System.', '["Case Management", "Document Repository", "Clerk Dashboard"]'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM releases);
