-- Create table for support requests
CREATE TABLE IF NOT EXISTS public.support_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(), -- If using Supabase Auth
  user_email TEXT, -- For manual entry or fallback
  type TEXT NOT NULL CHECK (type IN ('Feature Request', 'Bug Report', 'General Inquiry', 'Other')),
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  priority TEXT DEFAULT 'Medium' CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')),
  status TEXT DEFAULT 'Open' CHECK (status IN ('Open', 'In Progress', 'Resolved', 'Closed')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.support_requests ENABLE ROW LEVEL SECURITY;

-- Policy: Users can see their own requests
CREATE POLICY "Users can view own support requests" 
ON public.support_requests FOR SELECT 
USING (auth.uid() = user_id OR user_email = current_user);

-- Policy: Users can insert their own requests
CREATE POLICY "Users can insert support requests" 
ON public.support_requests FOR INSERT 
WITH CHECK (true);

-- Policy: Admins can view all (assuming admin role or similar logic, for now open to authenticated for simplicity if admin logic isn't strict yet)
-- Ideally: 
-- CREATE POLICY "Admins can view all" ON public.support_requests FOR ALL USING (public.is_admin());
