-- Create table for support requests
CREATE TABLE IF NOT EXISTS public.support_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID DEFAULT auth.uid(), -- If using Supabase Auth
  user_email TEXT, -- For manual entry or fallback
  type TEXT NOT NULL CHECK (type IN ('Feature Request', 'Bug Report', 'General Inquiry', 'Other')),
  subject TEXT NOT NULL,
  message TEXT NOT NULL,
  priority TEXT DEFAULT 'Medium' CHECK (priority IN ('Low', 'Medium', 'High', 'Critical')),
  status TEXT DEFAULT 'Open' CHECK (status IN ('Open', 'In Progress', 'Resolved', 'Closed')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.support_requests ENABLE ROW LEVEL SECURITY;

-- Drop potentially conflicting old policies
DROP POLICY IF EXISTS "Users can view own support requests" ON public.support_requests;
DROP POLICY IF EXISTS "Users can insert support requests" ON public.support_requests;
DROP POLICY IF EXISTS "Allow authenticated view all support requests" ON public.support_requests;
DROP POLICY IF EXISTS "Allow authenticated insert support requests" ON public.support_requests;

-- Policy: Allow authenticated users to view ALL support requests (matches 'cases' table logic)
-- This simplifies permissions and ensures logged-in users (Clerks/Admins) can see the list.
CREATE POLICY "Allow authenticated view all support requests" ON public.support_requests
FOR SELECT TO authenticated USING (true);

-- Policy: Allow authenticated users to insert requests
CREATE POLICY "Allow authenticated insert support requests" ON public.support_requests
FOR INSERT TO authenticated WITH CHECK (true);
