-- Create table for Interim Orders
CREATE TABLE IF NOT EXISTS public.interim_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_name TEXT,
    case_no INTEGER,
    case_year INTEGER,
    undated_text TEXT,
    next_date DATE,
    order_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.interim_orders ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
CREATE POLICY "Allow read access for authenticated users" ON public.interim_orders
    FOR SELECT TO authenticated USING (true);

-- Allow insert/update/delete for authenticated users
CREATE POLICY "Allow write access for authenticated users" ON public.interim_orders
    FOR ALL TO authenticated USING (true);

-- Allow public read access (for unauthenticated users if needed)
CREATE POLICY "Allow public read access" ON public.interim_orders
    FOR SELECT TO public USING (true);
